project:
  type: book
  output-dir: docs

book:
  title: "The Little Handbook for MTPPR"
  subtitle: '**M**ulti-**T**rait **P**oint **P**attern **R**econstruction'
  author: 
    - Chris Wudel
  
  date: "07/07/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - simple_application_example.qmd
    - further_application_examples.qmd
    - specialized_application.qmd
    - summary_references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

